### ISSUE TITLE
User Story: Deployment

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#10]
As a **Developer**, I want to **deploy the project to Heroku early**, so that **I will be sure the deployed site is working in production environment** 

## Tasks
- [ ] Task 1 – install the heroku CLI
- [ ] Task 2 - Install Django-allauth for account authentication, registration and management
- [ ] Task 3 - Install Pillow – for images
- [ ] Task 4 – install Stripe – for our payment solution
- [ ] Task 5 - Install gunicorn to act as web server 
- [ ] Task 6 - Install django-crispy-forms to style forms
- [ ] Task 7 - Install Django-countries to provide country choices for forms
- [ ] Task 8 - Install dj_database_url and psycopg2 to connect to external database.
- [ ] Task 9 - Install boto3 and django-storages to connect Django to our S3.
- [ ] Task 10 - Create requirements file
- [ ] Task 11 - Create a new Heroku App
- [ ] Task 12 - Create a new database in ElephantSQL
- [ ] Task 13 - Copy the database URL from the database instance name for this project
- [ ] Task 14 - Set up a new AWS S3 bucket to securely store static files and images 
- [ ] Task 15 - Add DATABASE_URL from ElephantSQL, Django Secret Key, AWS S3 bucket Access Key and Secret Access Key to Heroku Config Vars
- [ ] Task 16 - Set to deploy automatically to Heroku when Push to Github
- [ ] Task 17 - Add hostname of Heroku app to ALLOWED_HOSTS in settings.py
- [ ] Task 18 – Configure settings.py file to connect to the new ElephantSQL database, to access our AWS S3 bucket, and to point at the correct env.py file in development
- [ ] Task 19 - In settings.py, replace DEBUG with DEBUG = 'DEVELOPMENT' in os.environment
- [ ] Task 20 – Add the AWS S3 bucket details to the env.py file 
- [ ] Task 21 - Create a Procfile for Heroku to create a web dyno to run gunicorn and serve our app 
- [ ] Task 22 - Create a superuser for the new database
