### ISSUE TITLE
User Story: Account Registration 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#11]
As a **new User**, I want to **register by creating a username and password** so that **I can save my personal details and have access to featured products.**

# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a new user
and I’m on the Sign-Up page
**When** I enter mandatory registration information (Email, Username, Password)
and I click the Sign-Up button
**Then** I can see a confirmation message that I have to verify my email address and I’m able to confirm my email address.
* Acceptance Criteria 2:
**Given** that I’m a new user
and I’m confirmation page for users to confirm their email address
**When** I click the Confirm button to verify my email address
**Then** I can see a confirmation message that an account has been created for me successfully
* Acceptance Criteria 3:
**Given** that I’m a user
and I’m on the Sign-Up page
**When** I enter my Email address or Username and Password
and I click the Sign-Up button
**Then** I am not registered and I can see an error message that a user is already registered with this e-mail address.
* Acceptance Criteria 4:
**Given** that I’m a new user
and I’m on the Sign-Up page
**When** I enter my Email address, preferred Password, and Username that already exist and I click the Sign-Up button
**Then** I am not registered and I can see an error message that a user with that username already exists. 
* Acceptance Criteria 5
**Given** that I’m a new user
and I’m on the Sign-Up page with a social Login
**When** I click my social media account 
**Then** I am logged into my account and I can see a confirmation message that the system signs me in. 

## Tasks
- [ ] Task 1 – Create a link to a Sign-Up page
- [ ] Task 2 - Design a Sign-Up form for users to enter their registration details
- [ ] Task 3 - Implement a method to validate the user registration data and to prevent multiple accounts creation with same username and email address.
- [ ] Task 4 – Implement a method to send confirmation email to new accounts.
- [ ] Task 5 – Create a confirmation page for users to confirm their email address
- [ ] Task 6 - Create a method to redirect the new user to the home page on successful registration.
