### ISSUE TITLE
User Story: Account Login 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#12]
As a **role**, I want to **capability**, so that **received benefit**
As a **registered User**, I want to **be able to sign in to my account** so that **I can have access to my personal profile.**

# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a registered user
and I’m on the Sign-In page
**When** I enter my Email address or Username and Password
and I click the Sign-In button
**Then** I am logged in to my account so that I can access my personal account information and I can see a successfully signed in message.
* Acceptance Criteria 2:
**Given** that I’m a registered user
and I’m on the Sign-In page
**When** I enter a wrong Email address or Username, or Password 
and I click the Sign-In button
**Then** I am not logged in and I can see an error message that the e-mail address and/or password I specified are not correct.
* Acceptance Criteria 3:
**Given** that I’m a registered user
and I’m on the Sign-In page
**When** I enter my login details and check “Remember Me” checkbox
and I click the Sign-In button
**Then** I am logged in and I can always have automatic access to my account from the same system until I manually sign out
* Acceptance Criteria 4
**Given** that I’m a registered user
and I’m on the Sign-In page
**When** I click the “Forgot Password?” link
**Then** I can reset my password if I’ve forgotten it or I want to update it for security reasons.

## Tasks
- [ ] Task 1 – Create a link to a Sign-In page
- [ ] Task 2 - Create a Sign-In form for registered users to enter their login details
- [ ] Task 3 - Implement a method to validate the user data matches a user account
- [ ] Task 4 - Develop a method to highlight an error message in red color below the form field. 
- [ ] Task 5 - Create a method to redirect the new user to the home page on successful sign in.
- [ ] Task 6 – Implement a method to send confirmation email to new accounts.
- [ ] Task 7 – Implement a “remember me” functionality on login page.
- [ ] Task 8 – Implement a method to reset password on login page.
