### ISSUE TITLE
User Story: Account Logout 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#13]
As a **User**, I want to **be able log out of my account**, so that **I can keep my account secure**
# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a registered user
and I’m logged into my account
**When** I click the logout link
**Then** I can see a visual confirmation page to confirm that I want to sign out.
* Acceptance Criteria 2:
**Given** that I’m a registered user
and I’m on confirmation page to confirm that I want to sign out
**When** I click the sign out button to confirm I want to logout
**Then** I am logged out of my account and I can see a visual confirmation that I have been logged out.

## Tasks
- [ ] Task 1 – Create a link to a Logout functionality
- [ ] Task 2 - Create a confirmation page for users to confirm they want to sign out.
- [ ] Task 3 - Create a method to redirect the user to the home page on successful sign out.
