### ISSUE TITLE
User Story - Social Media Login 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#14]
As a **registered user**, I want to **sign up and login using my social account ID** so that **I can have a convenient alternative to login to my account**
# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a new user
and I’m on the Sign-Up page with a social Login (Facebook, Google, Apple)
**When** I click my preferred social media account 
**Then** I can sign up using my existing social account IDs so that I can access the application and I can see a successfully signed in message.
* Acceptance Criteria 2:
**Given** that I’m a registered user
and I’m on the Sign-Up page with a social Login (Facebook, Google, Apple)
**When** I click my preferred social media account 
**Then** I am logged in using my existing social account IDs so that I can access my personal account information and I can see a successfully signed in message

## Tasks
- [ ] Task 1 - Create a social Sign-Up feature for users to register with their social media accounts
- [ ] Task 2 - Create a method to redirect the new user to the home page on successful registration.
- [ ] Task 3 – Implement a method to send confirmation email to new accounts.

## EPIC #2
