### ISSUE TITLE
User Story: My Account 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#15]
As a **registered User**, I want to **be able to login to my personalized user profile**, so that **I can manage my personal information and view my order history.** 

# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a logged in User
**When** I click my account and I click Account Information link 
**Then** I can view my Personal Information.
* Acceptance Criteria 2:
**Given** that I’m a logged in User
**When** I click My Account and I click Account Information link 
**Then** I can edit my Personal Information.
* Acceptance Criteria 3:
**Given** that I’m a logged in User
and I’m on the Account Information page 
**When** I select to Delete Account
and click to confirm 
**Then** I can delete my Personal Information and close my account.

## Tasks
- [ ] Task 1:Task 1 - Create a user profile page
- [ ] Task 2 - Create a method for users to view their Account Information.
- [ ] Task 3 - Create a method for users to update their Account Information.
- [ ] Task 4 - Create a method for users to delete their Account.
- [ ] Task 5 - Account deletion will require a second level confirmation to take effect
