### ISSUE TITLE
User Story: My Address 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#16]
As a **User**, I want to **login to my personalized user profile**, so that **I can view Default Billing Address and Default Shipping Address.**

# Acceptance Criteria
* Acceptance Criteria 1:
Given that I’m a logged in User
When I click my account and I click My Address 
Then I can view Default Billing Address and Default Shipping Address
* Acceptance Criteria 2:
Given that I’m a logged in User
and I’m on my My Address page
When I click Change Default Billing Address
Then I can view and update my Default Delivery Information 
* Acceptance Criteria 3:
Given that I’m a logged in User
and I’m on my My Address page
When I click Default Shipping Address
Then I can view and update my Default Shipping Address

## Tasks
- [ ] Task 1 – Create a method for users to view a record of their Default Delivery Information and Default Shipping Address.
- [ ] Task 2 – Implement a method for users to update their Default Billing Information
- [ ] Task 3 – Implement a method for users to update their Default Delivery Information
