### ISSUE TITLE
User Story: My Orders 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#17]
As a **User**, I want to **login to my account**, so that **I can view My Orders**
# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a logged in User
**When** I click my account and I click My Orders 
**Then** I can view my order history.
* Acceptance Criteria 2:
**Given** that I’m a logged in User
and I have items in my cart
**When** I click the checkout button
**Then** I have my Default Delivery Information ready to be used

## Tasks
- [ ] Task 1 - Create a method for users to view a record of their order history.
- [ ] Task 2 – Implement a method for Default Billing Information to be prepopulated on checkout
- [ ] Task 3 – Implement a method for Default Delivery Information to be prepopulated on checkout

## EPIC #3
