### ISSUE TITLE
User Story: View Products 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#18]
As a **User**, I want to **view a list of products** so that **I can select the products to purchase.** 

# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a logged in User
and I am on the home page
**When** I click the Shop Now button 
**Then** I can see a list of all products in the store.
* Acceptance Criteria 2:
**Given** that I’m a logged in User
and I am on the products list page
**When** I click to view individual product details 
**Then** I can identify the price, description, detailed reviews, and product image.
* Acceptance Criteria 3:
**Given** that I’m a logged in User
and I am on the products list page
**When** I click a back-to-top button 
**Then** I am taken back to the top of the product list without having to scroll through hundreds of products.

## Tasks
- [ ] Task 1 - Create a page of a list of all products in the store.
- [ ] Task 2 - Create a method to view individual product details
- [ ] Task 3 - Implement a Back-to-top functionality in the products page
