### ISSUE TITLE
User Story – Sort and Search Product 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#19]
As a **User**, I want to **sort and search products**, so that **I can quickly find the products I want to purchase**.

- **Acceptance Criteria 1**
**Given** that I’m a logged in User
and I am on the products list page
**When** I see a product sort select box 
**Then** I can sort products by price, rating, name, or category.

- **Acceptance Criteria 2**
**Given** that I’m a User
**When** I select to view Products by Category
**Then** I will be able to choose any product I may want to buy.

- **Acceptance Criteria 3**
**Given** that I’m a User
**When** I can see the search bar at the top of the page in a visually distinguishable way
**Then** I can easily search for products from any page

- **Acceptance Criteria 4**
**Given** that I’m a User
and I can see the search bar in all the site pages
**When** I search products by name
**Then** I can find all the products that matches the search name.

## Tasks
- [ ] Task 1 – Implement product sort selector box option on the products page
- [ ] Task 2 - Implement a method for user to sort product by name
- [ ] Task 3 – Implement a method for user to sort product by price
- [ ] Task 4 – Implement a method for user to sort product by rating
- [ ] Task 5 – Implement a method for user to sort product by category
- [ ] Task 6 - Implement search bar functionality that is visible to the user on every page
- [ ] Task 7 – Implement a method for user to Search for a product by name
