### ISSUE TITLE
User Story – Manage Products 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#20]
As a **Superuser**, I want to **login to my user profile**, so that **I can manage all products in the store**. 

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m a logged in Superuser
**When** I click My Account 
and I click Product Management 
**Then** I can I can add a product to the store.

- **Acceptance Criteria 2**
**Given** that I’m a logged in Superuser
and I’m on Products page 
**When** I click the edit link 
and I click Product Management 
**Then** I can edit the product.

- **Acceptance Criteria 3**
**Given** that I’m a logged in Superuser
and I’m on Products page 
**When** I click the delete link 
and, I click to confirm the deletion request
**Then** I can delete the product and redirected to all-products page.

## Tasks
- [ ] Task 1 - Create a product form for store owner to add products in the store.
- [ ] Task 2 – Implement a method for store owner to edit products in the store
- [ ] Task 3 – Implement a method for store owner to delete products in the store
- [ ] Task 4 – Implement a method to secure the product management links
