### ISSUE TITLE
User Story - Wishlist

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#22]
As a **User**, I want to **add products to my Wishlist**, so that **I can save items I would like to have.**

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m a logged in User
**When** I’m on Products page 
**Then** I can add products to Wishlist.

- **Acceptance Criteria 2**
**Given** that I’m a logged in User
**When** I add products to my Wishlist
**Then** I can see the number of items on my Wishlist.

- **Acceptance Criteria 3**
**Given** that I’m a logged in User
and I have products in my cart
**When** I click the Add to Cart button
**Then** I can move the products from Wishlist to the cart ready for checkout

- **Acceptance Criteria 4**
**Given** that I’m a logged in User
**When** an item is on my Wishlist
**Then** I can delete the item if I’m no longer interested in it.

## Tasks
- [ ] Task 1 – Create a Wish List capability 
- [ ] Task 2 – Create a functionality to add products to Wishlist.
- [ ] Task 3 – Create a functionality to move products from Wishlist to the cart.
- [ ] Task 4 – Implement a functionality to track products in the Wishlist
- [ ] Task 5 – Develop a counter for number of Wishlist products added to shopping cart
- [ ] Task 6 – Create a functionality to delete items from Wishlist.
