### ISSUE TITLE
User Story - Purchase 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#23]
As a **User**, I want to **be able to add multiple items to a shopping cart**, so that **I can buy the products I want.**

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m a User
**When** I am on the product detail page
**Then** I have the option to add more than one individual item to the cart. 

- **Acceptance Criteria 2**
**Given** that I’m a User
**When** I add a product to the shopping cart
**Then** I will know the total cost of my purchases before checkout.

- **Acceptance Criteria 3**
**Given** that I’m a User
**When** I’m on the shopping cart page 
**Then** I can update or remove items on my shopping cart.

- **Acceptance Criteria 4**
**Given** that I’m a User
**When** I add a product to the shopping cart
**Then** I can checkout and buy the products I want.

## Tasks
- [ ] Task 1 – Create a shopping cart page
- [ ] Task 2 – Develop functionality to add products to the shopping cart
- [ ] Task 3 – Develop functionality to calculate delivery cost
- [ ] Task 4 – Develop functionality to track products in the shopping cart
- [ ] Task 5 – Develop a counter for number of products added to shopping cart
