### ISSUE TITLE
User Story – Checkout

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#25]
As a **User**, I want to **select a quantity of a product** so that **I can proceed to checkout to complete my order.**

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m an unregistered User
**When** I’m on the checkout page
**Then** I have the option to enter my payment and delivery details to complete my order.

- **Acceptance Criteria 2**
**Given** that I’m a User
**When** I’m on the checkout page
**Then** I have the option to save delivery information entered to my profile.

- **Acceptance Criteria 3**
**Given** that I’m a registered User
and I’m on the checkout page
**When** I enter my payment information  
**Then** I can check out using my Delivery Information stored in the system

- **Acceptance Criteria 4**
**Given** that I’m a User
**When** I checkout to finalize purchase 
**Then** I will see my Order confirmation page confirming a successful transaction.

- **Acceptance Criteria 5**
**Given** that I’m a User
**When** I checkout after making purchases 
**Then** I will receive an Order confirmation email for my records.

## Tasks
- [ ] Task 1 - Create a functionality on checkout page to save delivery information entered to profile
- [ ] Task 2 - Develop a functionality to generate an order number
- [ ] Task 3 - Create a functionality for Order confirmation page with order summary 
- [ ] Task 4 - Create a functionality to send Order confirmation email 
- [ ] Task 5 - Create a checkout link on shopping cart page
