### ISSUE TITLE
User Story – Reviews 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#26]
As a **User**, I want to **leave a review on purchased product** so that **I can provide feedback to store owner and other buyers.**

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m a logged in User
**When** I buy a product
**Then** I can write a review about the product.

- **Acceptance Criteria 2**
**Given** that I’m a logged in User
**When** I leave a review on product I purchased
**Then** I can view the review.

- **Acceptance Criteria 3**
**Given** that I’m a logged in User
**When** I leave a product review 
**Then** I can edit the review.

- **Acceptance Criteria 4**
**Given** that I’m a logged in User
**When** I leave a product review 
**Then** I can delete the review.

## Tasks
- [ ] Task 1 – Create a functionality that allows users to review products they purchased.
- [ ] Task 2 – Create a functionality that enable users to edit their product review.
- [ ] Task 3 – Create a functionality that enable users to delete their product review.
- [ ] Task 4 - Develop functionality to allow users review, edit, delete products they bought
- [ ] Task 5 – Develop a counter for number of product reviews
