### ISSUE TITLE
User Story – Ratings 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#27]
As a **User**, I want to **Like or Unlike products** so that **I will leave my rating of the product quality.**

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m a logged in User
**When** I am impressed with the product I bought
**Then** I can click to Like the product to leave positive feedback.

- **Acceptance Criteria 2**
**Given** that I’m a logged in User
**When** I am not impressed with the quality of the product I bought
**Then** I can Dislike the product to leave negative feedback.

## Tasks
- [ ] Task 1 – Create a functionality that allows users to rate products purchased.
- [ ] Task 2 – Create a functionality that enable users to Like products purchased.
- [ ] Task 3 – Create a functionality that enable users to Unlike products purchased.
- [ ] Task 4 - Develop functionality to allow users rate products they bought
- [ ] Task 5 – Develop a counter for number of products Likes and Dislikes
