### ISSUE TITLE
User Story - Email and Social Media Marketing 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#28]
As a **Store Owner**, I want to **send direct marketing messages to customers** so that **I can to promote my products and increase sales.**

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m a store owner
**When** I create newsletter forms to collect customers email address
**Then** I can send direct marketing emails to promote my products 

- **Acceptance Criteria 2**
**Given** that I’m a store owner
**When** I set up social media pages  
**Then** I send direct marketing messages to followers

- **Acceptance Criteria 3**
**Given** that I’m a store owner
**When** I set up a contact page for customers to contact me
**Then** I can generate more leads through email communication 

## Tasks
- [ ] Task 1 - Create newsletter signups hosted by Mailchimp.
- [ ] Task 3 - Create functionality to send promotional emails 
- [ ] Task 2 – Create Facebook, Instagram or Twitter pages to promote products
- [ ] Task 4 - Create contact page for direct contact from customers
- [ ] Task 5 – Add Subscribe to Newsletter checkbox to contact form
