### ISSUE TITLE
User Story - Search Engine Optimization 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#29]
As a **Developer**, I want to **optimise my e-commerce website for Search Engine Optimization** so that **I can improve its search engine rankings.**

# Acceptance Criteria
- **Acceptance Criteria 1**
**Given** that I’m a Shop Owner 
**When** I apply semantic HTML elements and descriptive meta tags in the HTML
**Then** search engines can rank my site highly enough to show up on their first page.

- **Acceptance Criteria 2**
**Given** that I’m a Shop Owner 
**When** I create informed and trustworthy your web page content
**Then** Keywords will help users find my site for higher rankings in search engines.

## Tasks
- [ ] Task 1 - Apply relevant keywords and descriptive meta tags in templates. 
- [ ] Task 2 - Generate a sitemap.xml file for search engines.
- [ ] Task 3 - Create a robots.txt file to manage crawl budget
- [ ] Task 4 - Test robots.txt file with the robots.txt Tester
- [ ] Task 5 - Create a privacy policy statement page 
- [ ] Task 6 - Create a terms of service page 
- [ ] Task 7 - Create a terms and conditions page
