### ISSUE TITLE
USER STORY - Handle Errors and Notifications 

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#31]
As a **Store Owner**, I want to **implement logics to handle errors and notifications**, so that **the site will reduce customer frustration and enhance user experience.** 

# Acceptance Criteria
* Acceptance Criteria 1:
**Given** that I’m a store owner
**When** I create 404 page to handle page not found error
**Then** user will use the link provided if a given page was not found 
* Acceptance Criteria 2:
**Given** that I’m a store owner
**When** I create 500 page to handle internal server error
**Then** user will know it was a system error and need to try again 
* Acceptance Criteria 3:
**Given** that I’m a store owner
**When** I set up bootstrap toast  
**Then** I give users real-time notifications on their actions as they browse our store.

## Tasks
- [ ] Task 1: Create 404 page to handle page not found error
- [ ] Task 2: Create 500 page to handle internal server error
- [ ] Task 3: Implement alert messages to give feedback to the user
