### ISSUE TITLE
User Story: Setup Project

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio5-bessie-beau#9]
As a **role**, I want to **setup the Django project Environment**, so that **I can initialise the development environment and deploy early**

## Tasks
- [ ] Task 1 - Create GitHub repository to store project files online and clone to VSCode
- [ ] Task 2 -  Create User Project in GitHub to use Kanban feature to handle User Stories
- [ ] Task 3 - Add our user stories in the issues tab
- [ ] Task 4 - Create and activate Virtual Environment on local machine 
- [ ] Task 5 - Install Django
- [ ] Task 6 - Create env file to hide sensitive data and include the file in a .gitignore file
- [ ] Task 7 - Install pycodestyle for python style guide checking
- [ ] Task 8 - Install pylint to check code errors and enforce coding standard
- [ ] Task 9 - Install flake8-django to enforce PEP8 compliance specific to Django projects
- [ ] Task 10 - Create a requirements.txt file to let heroku know which packages to install
- [ ] Task 11 - Create the Django project
- [ ] Task 12 - Create the first app and add to installed apps
- [ ] Task 13 - Create home app and set up base.html
